name: Deploy Lambda Function

on:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  build:
    name: Build Lambda ZIP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install dependencies
        run: |
          cd lambda_function
          npm install

      - name: Create lambda.zip
        run: |
          cd lambda_function
          zip -r ../lambda.zip .

  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest
    needs: build
    environment: dev # Directly specifying the environment as 'dev'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.4.5"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}

      - name: Terraform init
        run: |
          cd infrastructure
          terraform init -backend-config=environments/dev/backend-config.hcl

      - name: Terraform plan
        run: |
          cd infrastructure
          terraform plan -var-file=environments/dev/terraform.tfvars

      - name: Terraform apply
        run: |
          cd infrastructure
          terraform apply -var-file=environments/dev/terraform.tfvars -auto-approve

  notify:
    name: Notify success/failure
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Notify success/failure status
        run: echo "Lambda deployment to ${{ job.environment }} environment completed successfully."
